runtime: java
env: flex
manual_scaling:
  instances: 1
handlers:
  - url: /.*
    script: this field is required, but ignored

readiness_check:
  app_start_timeout_sec: 1800

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5
